### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by skyland06** [dmolik/tls-server#1]
[root@HDM tls-server]# make
cc -Wall -Wextra -pipe -pedantic -std=c99 -g -lcrypto -lssl -lpthread  -o server src/server.o src/daemon.o src/log.o src/utils.o src/parse.o src/scanner.o src/main.o
cc: src/server.o: No such file or directory
cc: src/daemon.o: No such file or directory
cc: src/log.o: No such file or directory
cc: src/utils.o: No such file or directory
cc: src/parse.o: No such file or directory
cc: src/scanner.o: No such file or directory
cc: src/main.o: No such file or directory
make: *** [server] Error 1
[root@HDM tls-server]# ls src/
client.c  config_file.h  daemon.c  daemon.h  gen_cert.c  log.c  log.h  main.c  parse.y  scanner.l  server.c  server.h  utils.c  utils.h
[root@HDM tls-server]#

**Comment by dmolik** [comment]
Is this on a fresh clone? Try doing a `make clean`

**Comment by dmolik** [comment]
it's been over 6 months, please get back to me within a week, otherwise I'm going to go ahead and close this.
